spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kerdy
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    show-sql: true
  config:
    activate:
      on-profile: default

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

github:
  client:
    id: client_id
    secret: client_secret
  url:
    access-token: access-token_url
    profile: profile_url

security:
  jwt:
    token:
      secret-key: secret_key
      expire-length: 3_600_000_000

firebase:
  project:
    id: kerdy

data:
  admin-url: http://localhost:3000

---

spring:
  config:
    import: classpath:kerdy-submodule/application-dev.yml
    activate:
      on-profile: dev

---

spring:
  config:
    import: classpath:kerdy-submodule/application-prod.yml
    activate:
      on-profile: prod

